import { getPrismaClient } from '@cwm/db'
import { KnowledgeEntrySchema, type KnowledgeEntry, type KnowledgeEntryInput } from '@cwm/config'

/** Converte input do usuário em query FTS5 segura com prefix matching. */
function buildFtsQuery(raw: string): string {
  const words = raw.trim()
    .replace(/['"()^{}[\]|&;:!?]/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
    .map(w => `${w}*`)
  return words.join(' ')
}

export class KnowledgeService {
  private get db() { return getPrismaClient() }

  async list(): Promise<KnowledgeEntry[]> {
    return this.db.knowledgeEntry.findMany({ orderBy: { updatedAt: 'desc' } }) as Promise<KnowledgeEntry[]>
  }

  async listActive(): Promise<KnowledgeEntry[]> {
    return this.db.knowledgeEntry.findMany({
      where: { isActive: true },
      orderBy: { category: 'asc' },
    }) as Promise<KnowledgeEntry[]>
  }

  async create(input: KnowledgeEntryInput): Promise<KnowledgeEntry> {
    const data = KnowledgeEntrySchema.parse(input)
    return this.db.knowledgeEntry.create({ data }) as Promise<KnowledgeEntry>
  }

  async update(id: string, input: Partial<KnowledgeEntryInput>): Promise<KnowledgeEntry> {
    const data = KnowledgeEntrySchema.partial().parse(input)
    return this.db.knowledgeEntry.update({ where: { id }, data }) as Promise<KnowledgeEntry>
  }

  async delete(id: string): Promise<void> {
    await this.db.knowledgeEntry.delete({ where: { id } })
  }

  /**
   * Busca full-text via FTS5 com prefix matching.
   * Fallback automático para LIKE se o índice FTS ainda não existir.
   */
  async search(query: string, limit = 20): Promise<KnowledgeEntry[]> {
    if (!query.trim()) return []
    const ftsQuery = buildFtsQuery(query)
    if (!ftsQuery) return []
    try {
      const rows = await this.db.$queryRawUnsafe(
        `SELECT e.id, e.title, e.content, e.category, e.tags, e.isActive,
                e.source, e.projectId, e.relevanceScore, e.autoGenerated, e.usageCount,
                e.createdAt, e.updatedAt
         FROM knowledge_fts
         JOIN knowledge_entries e ON e.rowid = knowledge_fts.rowid
         WHERE knowledge_fts MATCH ?
         ORDER BY knowledge_fts.rank
         LIMIT ?`,
        ftsQuery, limit,
      ) as Record<string, unknown>[]
      return rows as unknown as KnowledgeEntry[]
    } catch {
      // FTS indisponível — fallback LIKE
      const q = `%${query.trim()}%`
      const rows = await this.db.$queryRawUnsafe(
        `SELECT * FROM knowledge_entries
         WHERE lower(title) LIKE lower(?) OR lower(content) LIKE lower(?) OR lower(tags) LIKE lower(?)
         ORDER BY updatedAt DESC LIMIT ?`,
        q, q, q, limit,
      ) as Record<string, unknown>[]
      return rows as unknown as KnowledgeEntry[]
    }
  }

  buildContextFromEntries(entries: KnowledgeEntry[], header = '## MEMÓRIAS RELEVANTES'): string {
    if (entries.length === 0) return ''
    const byCategory = new Map<string, KnowledgeEntry[]>()
    for (const e of entries) {
      const list = byCategory.get(e.category) ?? []
      list.push(e)
      byCategory.set(e.category, list)
    }
    const lines: string[] = [`${header}\n`]
    for (const [cat, items] of byCategory) {
      lines.push(`### ${cat.toUpperCase()}`)
      for (const item of items) {
        const tagStr = item.tags ? ` [${item.tags}]` : ''
        lines.push(`**${item.title}**${tagStr}`)
        lines.push(item.content)
        lines.push('')
      }
    }
    return lines.join('\n')
  }

  async buildContext(): Promise<string> {
    const entries = await this.listActive()
    return this.buildContextFromEntries(entries, '## BASE DE CONHECIMENTO DO DESENVOLVEDOR')
  }
}
