import { getPrismaClient } from '@cwm/db'

function buildFtsQuery(raw: string): string {
  const words = raw.trim()
    .replace(/['"()^{}[\]|&;:!?]/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
    .map(w => `${w}*`)
  return words.join(' ')
}

export interface AgentSkill {
  id: string
  title: string
  description: string
  category: string
  triggers: string[]
  content: string
  examples: string[]
  usageCount: number
  autoGenerated: boolean
  createdAt: Date
  updatedAt: Date
}

export interface AgentSkillInput {
  title: string
  description?: string
  category?: string
  triggers?: string[]
  content: string
  examples?: string[]
  autoGenerated?: boolean
}

const SKILL_CATEGORIES = ['geral', 'desenvolvimento', 'devops', 'debug', 'arquitetura', 'snippets'] as const

function parseSkillRow(row: Record<string, unknown>): AgentSkill {
  let triggers: string[] = []
  let examples: string[] = []
  try { triggers = JSON.parse(row['triggers'] as string) } catch { triggers = [] }
  try { examples = JSON.parse(row['examples'] as string) } catch { examples = [] }
  return {
    id: row['id'] as string,
    title: row['title'] as string,
    description: (row['description'] as string) ?? '',
    category: (row['category'] as string) ?? 'geral',
    triggers,
    content: (row['content'] as string) ?? '',
    examples,
    usageCount: (row['usageCount'] as number) ?? 0,
    autoGenerated: ((row['autoGenerated'] as number) ?? 0) === 1,
    createdAt: new Date(row['createdAt'] as string),
    updatedAt: new Date(row['updatedAt'] as string),
  }
}

export { SKILL_CATEGORIES }

export class SkillsService {
  private get db() { return getPrismaClient() }

  async list(): Promise<AgentSkill[]> {
    const rows = await this.db.$queryRawUnsafe(
      `SELECT * FROM agent_skills ORDER BY usageCount DESC, updatedAt DESC`
    ) as Record<string, unknown>[]
    return rows.map(parseSkillRow)
  }

  async get(id: string): Promise<AgentSkill | null> {
    const rows = await this.db.$queryRawUnsafe(
      `SELECT * FROM agent_skills WHERE id=? LIMIT 1`, id
    ) as Record<string, unknown>[]
    return rows[0] ? parseSkillRow(rows[0]) : null
  }

  async create(input: AgentSkillInput): Promise<AgentSkill> {
    const id = crypto.randomUUID()
    const now = new Date().toISOString()
    const category = SKILL_CATEGORIES.includes(input.category as typeof SKILL_CATEGORIES[number])
      ? input.category!
      : 'geral'
    await this.db.$executeRawUnsafe(
      `INSERT INTO agent_skills (id, title, description, category, triggers, content, examples, autoGenerated, createdAt, updatedAt)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      id,
      input.title.trim(),
      (input.description ?? '').trim(),
      category,
      JSON.stringify(input.triggers ?? []),
      input.content,
      JSON.stringify(input.examples ?? []),
      input.autoGenerated ? 1 : 0,
      now,
      now,
    )
    return (await this.get(id))!
  }

  async update(id: string, input: Partial<AgentSkillInput>): Promise<AgentSkill> {
    const existing = await this.get(id)
    if (!existing) throw new Error('Skill não encontrada')
    const now = new Date().toISOString()
    const category = input.category && SKILL_CATEGORIES.includes(input.category as typeof SKILL_CATEGORIES[number])
      ? input.category
      : existing.category
    await this.db.$executeRawUnsafe(
      `UPDATE agent_skills SET title=?, description=?, category=?, triggers=?, content=?, examples=?, updatedAt=? WHERE id=?`,
      input.title?.trim() ?? existing.title,
      input.description?.trim() ?? existing.description,
      category,
      JSON.stringify(input.triggers ?? existing.triggers),
      input.content ?? existing.content,
      JSON.stringify(input.examples ?? existing.examples),
      now,
      id,
    )
    return (await this.get(id))!
  }

  async delete(id: string): Promise<void> {
    await this.db.$executeRawUnsafe(`DELETE FROM agent_skills WHERE id=?`, id)
  }

  async search(query: string, limit = 20): Promise<AgentSkill[]> {
    if (!query.trim()) return this.list()
    const ftsQuery = buildFtsQuery(query)
    if (!ftsQuery) return this.list()
    try {
      const rows = await this.db.$queryRawUnsafe(
        `SELECT e.id, e.title, e.description, e.category, e.triggers, e.content,
                e.examples, e.usageCount, e.autoGenerated, e.createdAt, e.updatedAt
         FROM skills_fts
         JOIN agent_skills e ON e.rowid = skills_fts.rowid
         WHERE skills_fts MATCH ?
         ORDER BY skills_fts.rank
         LIMIT ?`,
        ftsQuery, limit,
      ) as Record<string, unknown>[]
      return rows.map(parseSkillRow)
    } catch {
      // Fallback LIKE enquanto FTS não está disponível
      const q = `%${query.trim().toLowerCase()}%`
      const rows = await this.db.$queryRawUnsafe(
        `SELECT * FROM agent_skills
         WHERE lower(title) LIKE ? OR lower(description) LIKE ? OR lower(content) LIKE ? OR lower(triggers) LIKE ?
         ORDER BY usageCount DESC, updatedAt DESC LIMIT ?`,
        q, q, q, q, limit,
      ) as Record<string, unknown>[]
      return rows.map(parseSkillRow)
    }
  }

  async matchTriggers(text: string): Promise<AgentSkill[]> {
    if (!text.trim()) return []
    const all = await this.list()
    const lower = text.toLowerCase()
    return all.filter(skill =>
      skill.triggers.length > 0 &&
      skill.triggers.some(t => lower.includes(t.toLowerCase()))
    )
  }

  async incrementUsage(id: string): Promise<void> {
    await this.db.$executeRawUnsafe(
      `UPDATE agent_skills SET usageCount = usageCount + 1, updatedAt=? WHERE id=?`,
      new Date().toISOString(), id,
    )
  }

  buildContext(skills: AgentSkill[]): string {
    if (skills.length === 0) return ''
    const lines = ['## SKILLS DISPONÍVEIS\n']
    for (const s of skills) {
      lines.push(`### ${s.title} [${s.category}]`)
      if (s.description) lines.push(s.description)
      if (s.triggers.length) lines.push(`*Gatilhos: ${s.triggers.join(', ')}*`)
      lines.push('')
      lines.push(s.content)
      lines.push('')
    }
    return lines.join('\n')
  }
}
